title: lomayd
description: Web Server Engineer
site_title: '@lomayd - Jinho Kim'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: lomayd
blog_url:
email: jinho10167@gmail.com
keybase_username:
twitter_username:
reddit_username:

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 